name: Tests

env:
  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#  MYSQL_ATTR_SSL_CA: ${{ secrets.MYSQL_ATTR_SSL_CA }}

on:
  workflow_dispatch:
  pull_request:
      branches: [ main ]

jobs:
  Laravel-Pint-And-Unit-Tests-Checks:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Cache Composer dependencies
      - name: Cache Composer Dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      # Setup PHP
      - uses: shivammathur/setup-php@master
        with:
          php-version: '8.3'

      # Install Dependencies (only if cache miss)
      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      # Laravel Pint Check
      - name: "Laravel Pint Check"
        uses: aglipanci/laravel-pint-action@latest
        with:
          testMode: true
          configPath: "pint.json"

      # Copy .env file
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Generate application key
      - name: Generate key
        run: php artisan key:generate

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Run PHPUnit tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
